### ISSUE TITLE
Improve sidebar placement

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#30]
There are (at least) three kinds of sidebars:

1. Table of contents
2. Menus (e.g. Development menu)
3. Plugin/component info boxes

All of these should be located in the left and/or right margins, to avoid displacing the main narrative text.

Here is a rough first cut at some CSS rules that start going in the direction I have in mind:

```css
.toc {
position: absolute;
left: 0;
font-size: 0.75em;
width: 240px;
DELETE -- margin-right
DELETE -- max-width
DELETE -- margin-bottom
}

.container {
margin: 0 200px; // the 200px is left & right margin... for sidebars
DELETE? -- max-width: calc(100% - 4em);
DELETE? -- width: 60em;
}

#content {
 // check this!
}
.page-content {
 // check this!
}

#info-box {
DELETE -- float: right;
DELETE -- min-width: 500px;
position: absolute;
right: 0;
width: 240px;
font-size: 0.75em;
}

.table-info { // main.css:3237
  DELETE -- width: 80%;
  DELETE -- margin: 0 10%;
}

.main { // main.css:4007 (and main.css:3483)
padding: 0;
}
```

Maybe we can use [absolute positioning inside relative positioning](https://css-tricks.com/absolute-positioning-inside-relative-positioning/) or similar tricks to put multiple sidebars vertically sequentially without overlapping?

One problem is that when screen width gets narrow (e.g. mobile phones), the margins disappear, and these sidebars will need to become sandwich menus or else "pop in" to the main column. Further development and experimentation needed to develop a good set of CSS rules.

If no one else is comfortable doing this while I'm away, I'll work on it later this fall.
